name: dash_chan_packages_workspace
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/dash-chan/packages

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  melos: ^3.0.1
  test: ^1.21.0
