name: aaps
description: "A Flutter FFI plugin to retrieve the installed app list."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  android_os_build: ^0.0.3
  flutter:
    sdk: flutter
  jni: ^0.10.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  jnigen: ^0.10.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
