name: pattern_dots
description: A pattern lock UI using flutter.
version: 0.0.1-alpha
repository: https://github.com/dash-chan/packages/tree/main/packages/pattern_dots
issue_tracker: https://github.com/dash-chan/packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+pattern_dots%22

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: