name: loggable_json
description: print json with colorful output.
version: 1.0.1
repository: https://github.com/dash-chan/packages/tree/main/packages/json_printer

environment:
  sdk: ^3.5.0

dependencies:
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
