name: android_os_build
description: "android information about the current build, extracted from system properties.built with dart's experimental jnigen"
version: 0.0.2
repository: https://github.com/laihz/android_os_build
issue_tracker: https://github.com/laihz/android_os_build/issues
documentation: https://pub.dev/documentation/android_os_build/latest/
topics:
  - android
  - ffi
  - utils

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.10.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  jnigen: ^0.10.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
