name: android_os_build
description: "Easily retrieve information about the current Android build synchronously. Built with dart's experimental jni"
version: 0.3.0+1
repository: https://github.com/dash-chan/packages/tree/main/packages/android_os_build
issue_tracker: https://github.com/dash-chan/packages/labels/p%3Aandroid_os_build
documentation: https://pub.dev/documentation/android_os_build/latest/
screenshots:
  - description: 'Android Build'
    path: screenshots/android-head_3D.png
topics:
  - android
  - ffi
  - utils

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.14.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
