name: json_printer
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/dash-chan/packages/tree/main/packages/json_printer

environment:
  sdk: ^3.5.0

dependencies:
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
