// Autogenerated from Pigeon (v12.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GmsPlacesApi {
  func autocomplete(fromQuery: String) throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GmsPlacesApiSetup {
  /// The codec used by GmsPlacesApi.
  /// Sets up an instance of `GmsPlacesApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GmsPlacesApi?) {
    let autocompleteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gms_places_api.GmsPlacesApi.autocomplete", binaryMessenger: binaryMessenger)
    if let api = api {
      autocompleteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fromQueryArg = args[0] as! String
        do {
          let result = try api.autocomplete(fromQuery: fromQueryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      autocompleteChannel.setMessageHandler(nil)
    }
  }
}
